language: node_js
node_js:
  - "4.2"
  - "0.12"
  - "0.10"
env:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=Yt2xPFEXtr1s0340c3aTXhzUCW5JAXzcw
before_install: npm install -g grunt-cli
install: npm install
script: npm run-script test-on-travis
