language: node_js
node_js:
  - "0.12"
  - "0.10"
env:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=QhyX5ahDMn1iQj3Jtx1Btx9sM9GY1wsSv
before_install: npm install -g grunt-cli
install: npm install
script: npm run-script test-on-travis
